MBL-26 add new get hooks

diff --git a/frontend/.githooks/pre-push b/frontend/.githooks/pre-push
--- a/frontend/.githooks/pre-push
+++ b/frontend/.githooks/pre-push
@@ -1,10 +1,35 @@
 #!/usr/bin/env bash
-flutter analyze .
-if [ $? -ne 0 ]; then 
-    exit 1
-fi
 
-flutter test ./test/
-if [ $? -ne 0 ]; then 
-    exit 1
+printf "\e[33;1m%s\e[0m\n" 'Pre-Push'
+
+# Undo the stash of the files
+pop_stash_files () {
+    if [ -n "$hasChanges" ]; then
+        printf "\e[33;1m%s\e[0m\n" '=== Applying git stash changes ==='
+        git stash pop
+    fi
+}
+
+# Flutter Analyzer
+printf "\e[33;1m%s\e[0m\n" '=== Running Flutter analyzer ==='
+flutter analyze
+if [ $? -ne 0 ]; then
+  printf "\e[31;1m%s\e[0m\n" '=== Flutter analyzer error ==='
+  pop_stash_files
+  exit 1
 fi
+printf "\e[33;1m%s\e[0m\n" 'Finished running Flutter analyzer'
+printf '%s\n' "${avar}"
+
+# Unit tests
+printf "\e[33;1m%s\e[0m\n" '=== Running Unit Tests ==='
+flutter test
+if [ $? -ne 0 ]; then
+  printf "\e[31;1m%s\e[0m\n" '=== Unit tests error ==='
+  pop_stash_files
+  exit 1
+fi
+printf "\e[33;1m%s\e[0m\n" 'Finished running Unit Tests'
+printf '%s\n' "${avar}"
+
+pop_stash_files
